# Generated by Django 6.0 on 2025-12-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="form_completed",
            field=models.BooleanField(default=False),
        ),
    ]
