# Generated by Django 6.0 on 2025-12-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_user", "0002_profile_form_completed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="points",
            new_name="xp_points",
        ),
        migrations.AddField(
            model_name="profile",
            name="badges",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="level_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="profile",
            name="degree",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="end_goal",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="time_available",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
