# Generated by Django 6.0 on 2025-12-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_user", "0003_rename_points_profile_xp_points_profile_badges_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="badges",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="level_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="xp_points",
        ),
    ]
