# Generated by Django 6.0 on 2025-12-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "login_user",
            "0004_remove_profile_badges_remove_profile_level_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="roadmap",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
